/*
The guessing project in C++ is a game designed to test the player’s luck and knowledge.
The player needs to guess a random number generated by the computer. If the player guesses right, they will win a certain amount of money.
The winning prize depends on the difficulty of the game. The program implements classes, functions, and user-defined data types.
It also uses other features such as loops and conditionals to create a logical structure. Furthermore, it makes use of the standard template library to implement basic operations and other data structures.
*/

#include "functions.h"
using namespace std;

int main() {
	int guess;

	srand((unsigned)time(NULL));

	int random;

	for (int i = 1; i <= 1; i++) {
		random = random = rand() % 10 + 1;
		cout << random << endl;
	}

	cin >> guess;

	if (guess == random) {
		cout << 1 << endl;
	}
	else if (guess != random) {
		cout << 2;
	}


	return 0;

}