/*
The guessing project in C++ is a game designed to test the player’s luck and knowledge.
The player needs to guess a random number generated by the computer. If the player guesses right, they will win a certain amount of money.
The winning prize depends on the difficulty of the game. The program implements classes, functions, and user-defined data types.
It also uses other features such as loops and conditionals to create a logical structure. Furthermore, it makes use of the standard template library to implement basic operations and other data structures.

Generate the random number
	easy X
		if you win add $5 
		$0 - $20
	medium X
		if you win add $10
		$21 - $100
	hard X
		if you win add $20 
		$101 - unspecified amount

Player information X
	Create a player class X
	Bank amount X
	Name X

Add a score board?

*/

#include "functions.h"

int main() {
	using namespace std;

	introduction();

	return 0;
}