/*
The guessing project in C++ is a game designed to test the player’s luck and knowledge.
The player needs to guess a random number generated by the computer. If the player guesses right, they will win a certain amount of money.
The winning prize depends on the difficulty of the game. The program implements classes, functions, and user-defined data types.
It also uses other features such as loops and conditionals to create a logical structure. Furthermore, it makes use of the standard template library to implement basic operations and other data structures.
*/

#include "functions.h"
using namespace std;

int main() {
	//In order for the randomNum function to work srand must me at the top of main cpp.
	srand((unsigned)time(NULL));

	//introduction();


	//do {
	//	easyMode();

	//	if (p.playerCash >= 30) {
	//		break;
	//	}

	//} while (win == true);

	//cout << "medium mode" << endl;
	//system("pause");

	//do {
	//	mediumMode();

	//	if (p.playerCash >= 100) {
	//		break;
	//	}

	//} while (win == true);

	//cout << "hard mode" << endl;
	//system("pause");

	//do {
	//	hardMode();
	//} while (win == true);


	/*
	It breaks out of the while loop when cash < 30 and win == true.
	It does not break out of the do while loop because win is still equal to true but, it does not repeat the while loop which is correct.
	*/
	do {

		while (p.playerCash < 30 && win == true) {
			easyMode();
		}

	} while (win == true);

}